// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCMC1lHSCrVD9IUne4rkQ9OvdpRhtw6A',
    appId: '1:1008693044364:web:c9b4ec92825e2cc96347a9',
    messagingSenderId: '1008693044364',
    projectId: 'atts-bae5c',
    authDomain: 'atts-bae5c.firebaseapp.com',
    storageBucket: 'atts-bae5c.firebasestorage.app',
    measurementId: 'G-E8MLCK1LLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlzLQhwFMeu5NFC1xjp--De00LvPSRbPY',
    appId: '1:1008693044364:android:fadb466b369dc8f16347a9',
    messagingSenderId: '1008693044364',
    projectId: 'atts-bae5c',
    storageBucket: 'atts-bae5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgaNBkcV_T_v1SgiqjsoeycCX1gjwxL5A',
    appId: '1:1008693044364:ios:3310620ad34d6a9f6347a9',
    messagingSenderId: '1008693044364',
    projectId: 'atts-bae5c',
    storageBucket: 'atts-bae5c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgaNBkcV_T_v1SgiqjsoeycCX1gjwxL5A',
    appId: '1:1008693044364:ios:3310620ad34d6a9f6347a9',
    messagingSenderId: '1008693044364',
    projectId: 'atts-bae5c',
    storageBucket: 'atts-bae5c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCMC1lHSCrVD9IUne4rkQ9OvdpRhtw6A',
    appId: '1:1008693044364:web:bb8033608bc020796347a9',
    messagingSenderId: '1008693044364',
    projectId: 'atts-bae5c',
    authDomain: 'atts-bae5c.firebaseapp.com',
    storageBucket: 'atts-bae5c.firebasestorage.app',
    measurementId: 'G-NHKEFKWW0H',
  );
}
